### ISSUE TITLE
Add repo fetchers to the docs

### ISSUE THREAD

**Issue by mike-solomon** [moderneinc/moderne-docs#151]
Right now, we [link out to the repo fetchers in the Moderne organization repo](https://github.com/moderneinc/moderne-organizations/tree/main/repo-fetchers) - but it sounds like we want that to live in the docs, too. This could potentially exist in a new customer quickstart guide - or perhaps in the configuring the orgs service docs?
```[tasklist]
### Tasks
- [ ] https://github.com/moderneinc/mass-ingest-example/pull/21
- [ ] https://github.com/moderneinc/moderne-organizations/pull/107
- [x] https://github.com/moderneinc/moderne-docs/commit/dc0046adbdd85e136d7eba9aab89d7743f89e30d
- [ ] https://github.com/moderneinc/moderne-organizations-multitenant/issues/212
```

**Comment by sjungling** [comment]
https://moderneinc.slack.com/archives/C06UVTSPD29/p1732033062558789?thread_ts=1732026514.686419&cid=C06UVTSPD29

taking @kmccarp's comment as the :bat: signal to move forward

**Comment by sjungling** [comment]
https://github.com/moderneinc/repository-fetchers

**Comment by sjungling** [comment]
really meant to assign myself https://github.com/moderneinc/moderne-organizations-multitenant/issues/212

**Comment by mike-solomon** [comment]
I'm gonna go ahead and close this - the air gapped CLI doc contains all of the relevant scripts and explanations. We link out to the shared repo fetcher repo in other locations.
